[git_status]
format = '([\[$ahead$behind\]]($style) )'

[nodejs]
style = "bold green"
format = "[$symbol$version]($style) "

[package]
format = "[$symbol $version]($style) "

[character]
success_symbol = "[❯](cyan)"
error_symbol = "[✖](red)"

[battery]
disabled = true
